name: planta_fisica
description: Aplicación para administrar los servicios de planta física de la universidad iberoamericana

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^0.13.4
  provider: ^6.0.2
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

